apiVersion: v1
kind: Pod
metadata:
name: nginx_basic
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: linuxserver/nginx
      ports:
        - containerPort: 80
          name: "nginx-http"
