---
- name: Install basic applications on systems
  hosts: all
  become: true

  tasks:
    - name: Update package cache and install essential packages
      apt:
        update_cache: yes
        name:
          - vim
          - screenfetch
          - tmux
        state: present

