---
- name: Install basic applications on systems.
  hosts: all
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install vim, screenfetch, and tmux
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - screenfetch
        - tmux
