---
- name: Uninstall basic applications on systems
  hosts: all
  become: true

  tasks:
    - name: Update package cache and uninstall essential packages
      apt:
        update_cache: yes
        name:
          - vim
          - screenfetch
          - tmux
        state: absent
